version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # Only for repos with a package.json
  # - package-ecosystem: npm
  #   directory: /
  #   schedule:
  #     interval: daily
