name: 📸Image Storage
description: Upload images to use in the README here
title: "[IMAGES]: "
labels: ["images"]
body:
  - type: markdown
    attributes:
      value: |
        Upload any images you want to use here by clicking and dragging. Then copy the generated URL to use.

  - type: textarea
    attributes:
      label: "Drag images here"
