name: ✅New Repository Checklist
description: New repositories should complete this checklist
title: "[CHECKLIST]: NEW REPOSITORY SETTINGS"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Congrats on creating a new repository! Please make sure your new repo meets these requirements.

  - type: checkboxes
    id: repo-items
    attributes:
      label: Have you added any of the following to your repo yet?
      description: You may select more than one.
      options:
        - label: README that follows guidelines
        - label: LICENSE
        - label: Global Codeowner
        - label: Branch Protection
        - label: dependabot
        - label: Repo Lint Action
        - label: CLA Assistant
        - label: CodeScan
        - label: Topics
        
  - type: markdown
    attributes:
      value: |
        If you weren't able to check all of the boxes, please see the [best practices documentation](https://github.com/initialstate/best-practice-resources) for detailed instructions on how to add each requirement.
