name: check-for-essential-files
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
jobs:
  check-for-codeowners-file:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check for CODEOWNERS
        id: codeowners_file
        uses: initialstate/file-check-action@v1
        with:
          file: ".github/CODEOWNERS"

      - name: CODEOWNERS file Output Test
        run: echo ${{ steps.codeowners_file.outputs.file_exists }}

      - name: CODEOWNERS file exists with content
        if: steps.codeowners_file.outputs.file_exists == 'true'
        run: echo CODEOWNERS file exists!

      - name: CODEOWNERS file does not exist
        if: steps.codeowners_file.outputs.file_exists == 'false'
        run: echo CODEOWNERS file does not exist!

  check-for-readme-file:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check for README.md
        id: readme_file
        uses: initialstate/file-check-action@v1
        with:
          file: "README.md"

      - name: README file Output Test
        run: echo ${{ steps.readme_file.outputs.file_exists }}

      - name: README file exists with content
        if: steps.readme_file.outputs.file_exists == 'true'
        run: echo README file exists!

      - name: README file does not exist
        if: steps.readme_file.outputs.file_exists == 'false'
        run: echo README file does not exist!

